use marxist_quote_core::config::{HorizontalAlign, VerticalAlign};

#[derive(Debug)]
pub enum AppInput {
    UpdateFont(String),
    UpdateFontSize(f32),
    UpdateLanguage(String),
    UpdateTextColor(String),
    UpdateBgColor(String),
    UpdateBgOpacity(f32),
    UpdateBgEnabled(bool),
    UpdateBgRounded(bool),
    UpdateBgFill(bool),
    UpdateStrokeColor(String),
    UpdateStrokeOpacity(f32),
    UpdateStrokeEnabled(bool),
    UpdateStrokeWidth(f32),
    UpdateShadowColor(String),
    UpdateShadowEnabled(bool),
    UpdateShadowOpacity(f32),
    UpdateShadowOffset(f32),
    UpdateShadowBlur(f32),
    UpdateShadowSize(f32),
    UpdateQuoteHAlign(HorizontalAlign),
    UpdateQuoteVAlign(VerticalAlign),
    UpdateAuthorHAlign(HorizontalAlign),
    UpdateAuthorName(usize, String),
    UpdateAuthorWeight(usize, u32),
    AddAuthor,
    RemoveAuthor(usize),
    DismissAuthorNote,
    Save,
    ShowInteractivePicker,
    FetchQuoteNow,
    SkipQuote,
}
